# Generated by Django 5.0.4 on 2024-05-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_myprojects_delete_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprojects',
            name='imageorganization',
            field=models.ImageField(upload_to='images/projects'),
        ),
    ]
